jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Build the app
      run: 'chmod +x gradlew

        ./gradlew build

        '
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
name: APK Build
on:
  repository_dispatch:
    types: trigger-ga___ci_build.yaml
