jobs:
  translate:
    if: ${{ github.head_ref == 'l10n_master' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: pr
      name: Get Pull Request Number
      run: echo "pull_request_number=$(gh pr view l10n_master --json number -q .number
        || echo "")" >> $GITHUB_OUTPUT
    - continue-on-error: true
      id: translate
      name: Translate
      uses: ./translation-validation-bot/
      with:
        pr: ${{ steps.pr.outputs.pull_request_number }}
    - continue-on-error: true
      name: Update PR description
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ steps.translate.outputs.content }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: Generate reverse translations
on:
  repository_dispatch:
    types: trigger-ga___translation_validation.yaml
